version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
  backend:
    # build: ./backend/
    image: haybuxx/kittygram_backend
    env_file: .env
    volumes:
      - media:/media
      - static:/backend_static
    depends_on:
      - db
  frontend:
    image: haybuxx/kittygram_frontend
    env_file: .env
    # build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    # build: ./nginx/
    image: haybuxx/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media